### ISSUE TITLE
Transaction awareness?

### ISSUE THREAD

**Issue by Adamantish** [civiccc/db-query-matchers#33]
If this were able to ignore rolled back queries it would be perfect for my needs.

If I'm integration testing a large save routine or any failing http request really I want to be sure that it has been done properly atomically. If the last command fails I want it all rolled back.

A line or a helper encompassing something like this can sit on all my error response tests
```ruby
expect { my_big_saver }.not_to make_database_queries(manipulative: true)
```

Except, of course, that doesn't work because the manipulative query is counted but not committed.

Would you welcome a PR to add an option for this?

**Comment by trotzig** [comment]
Hi @Adamantish! If you want to make a stab at making a PR for this, I'll be happy to review. I've never thought about this particular use-case, I've usually made assertions about data not being updated/added in the database for these types of events.

**Comment by dmitry** [comment]
@Adamantish any reasons not to:

```ruby
}.to make_database_queries(matching: /ROLLBACK/)
}.not_to make_database_queries(manipulative: true)
```

**Comment by Adamantish** [comment]
Can you explain how that works @dmitry ? I can't see how looking for the ROLLBACK would mean the manipulative query won't be registered?

**Comment by dmitry** [comment]
@Adamantish in your case ROLLBACK should be alone, as probably some INSERT/UPDATE/DELETE commands were used before the ROLLBACK. Sometimes it make sense to add `to make_database_queries(manipulative: true)` just to register that some commands were used to manipulate the data, but later it was rolled back. Ignoring rolled back queries only would be possible in case if it will accumulate all the SQL queries, and then cut the ones between `BEGIN` and `ROLLBACK`. Currently there are no collector, it just matches at the same time when the callback is raisen: https://github.com/civiccc/db-query-matchers/blob/master/lib/db_query_matchers/query_counter.rb#L41 This change will require to rewrite counter logic.

**Comment by Adamantish** [comment]
@dmitry Yes, I can see the impact/effort ratio isn't great for this: probably why I never got around to it. I still think it makes sense from a semantic position when talking about manipulative queries (a manipulative query which is rolled back is, from a correctness standpoint, the same as one that didn't happen).

**Comment by sds** [comment]
Going to close this due to age, but happy to merge a PR with tests!
