### ISSUE TITLE
Support Rails 7?

### ISSUE THREAD

**Issue by jrochkind** [civiccc/db-query-matchers#43]
gemspec does not currently allow Rails 7. 

https://github.com/civiccc/db-query-matchers/blob/827993f5d4319a475273cc33699a1af5ea0131a4/db-query-matchers.gemspec#L18

I would like to upgrade a project that uses this to Rails 7.

**Comment by sds** [comment]
Implemented in #42.

**Comment by jrochkind** [comment]
Thanks @sds!

I see 0.11.0 was just released too, thanks!
